version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      dev-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
